POST http://localhost:5000/api/auth/signup HTTP/1.1
content-type: application/json

{ 
    "full_name": "john doe", 
    "username": "johndee", 
    "password": "123456", 
    "confirm_password": "123456", 
    "gender": "female"
}